version: "3.9"
services:
  # Postgres database
  db:
    extends:
      file: common-compose.yml
      service: db
    ports:
      - 5432:5432
  website-dev:
    build:
      context: .
      dockerfile: ./website/Dockerfile.dev
    volumes:
      - ./website/app/package-lock.json:/usr/src/website/app/package-lock.json
      - .:/usr/src:ro
      - website-target:/usr/src/target
      - website-registry:/usr/local/cargo/registry
      - website-node_modules:/usr/src/website/app/node_modules
    depends_on:
      - sqs
      - db
    restart: always
    extends:
      file: common-compose.yml
      service: website
    environment:
      - RUST_LOG=debug
      - S3_ADDRESS=http://localhost:9000
  gameplay-dev:
    build:
      context: .
      dockerfile: ./workers/gameplay/dev-Dockerfile
    volumes:
      - .:/usr/src:ro
      - gameplay-target:/usr/src/target
      - gameplay-registry:/usr/local/cargo/registry
    depends_on:
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: gameplay
    environment:
      - RUST_LOG=debug
  builder-dev:
    build:
      context: .
      dockerfile: ./workers/builder/dev-Dockerfile
    volumes:
      - .:/usr/src:ro
      - builder-target:/usr/src/target
      - builder-registry:/usr/local/cargo/registry
    depends_on:
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: builder
    environment:
      - RUST_LOG=debug
  results-dev:
    build:
      context: .
      dockerfile: ./workers/results/dev-Dockerfile
    volumes:
      - .:/usr/src:ro
      - results-target:/usr/src/target
      - results-registry:/usr/local/cargo/registry
    depends_on:
      - db
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: results
    environment:
      - RUST_LOG=debug
  s3:
    extends:
      file: common-compose.yml
      service: s3
  createbuckets:
    depends_on:
      - s3
    extends:
      file: common-compose.yml
      service: createbuckets

  sqs:
    extends:
      file: common-compose.yml
      service: sqs
    ports:
      - 9324:9324

  nginx:
    extends:
      file: common-compose.yml
      service: nginx
    volumes:
      - ./dev-nginx.conf.template:/nginx.conf.template:ro
    ports:
      - 3000:80
      - 9000:9000
      - 9999:9999
    depends_on:
      - s3
      - sqs

volumes:
  database:
  minio:
  website-target:
  website-registry:
  website-node_modules:
  gameplay-target:
  gameplay-registry:
  builder-target:
  builder-registry:
  results-target:
  results-registry:
