services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/pokerbots
    command: sh -c "cd /usr/src/pokerbots/website/app && npm install && npm run dev"
    environment:
      - BACKEND_URL=http://backend:3000
    ports:
      - 5173:5173
    extends:
      file: common-compose.yml
      service: website
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/pokerbots
    ports:
      - 3000:3000
    command: sh -c "cd /usr/src/pokerbots/website/backend && cargo watch -x run"
    extends:
      file: common-compose.yml
      service: website
  builder:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/pokerbots
    command: sh -c "cd /usr/src/pokerbots/workers/builder && cargo watch -x run"
    extends:
      file: common-compose.yml
      service: builder
  gameplay:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/pokerbots
    command: sh -c "cd /usr/src/pokerbots/workers/gameplay && cargo watch -x run"
    extends:
      file: common-compose.yml
      service: gameplay
  results:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    volumes:
      - .:/usr/src/pokerbots
    command: sh -c "cd /usr/src/pokerbots/workers/results && cargo watch -x run"
    extends:
      file: common-compose.yml
      service: results
  db:
    ports:
      - 5432:5432
    extends:
      file: common-compose.yml
      service: db
  s3:
    ports:
      - 9000:9000
      - 9999:9999
    extends:
      file: common-compose.yml
      service: s3
  sqs:
    ports:
      - 9324:9324
      - 9325:9325
    extends:
      file: common-compose.yml
      service: sqs
  createbuckets:
    extends:
      file: common-compose.yml
      service: createbuckets

volumes:
  database:
    external: false
  minio:
    external: false
