version: "3.9"
services:
  # Postgres database
  db:
    extends:
      file: common-compose.yml
      service: db
    ports:
      - 5432:5432
  gameplay-dev:
    build:
      context: .
      dockerfile: ./workers/gameplay/Dockerfile.dev
    volumes:
      - .:/usr/src
      - ./.volumes/gameplay-target:/usr/src/target
      - ./.volumes/gameplay-registry/:/usr/local/cargo/registry
    depends_on:
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: gameplay
    environment:
      - RUST_LOG=debug
  builder-dev:
    build:
      context: .
      dockerfile: ./workers/builder/Dockerfile.dev
    volumes:
      - .:/usr/src
      - ./.volumes/builder-target:/usr/src/target
      - ./.volumes/builder-registry/:/usr/local/cargo/registry
    depends_on:
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: builder
    environment:
      - RUST_LOG=debug
  results-dev:
    build:
      context: .
      dockerfile: ./workers/results/Dockerfile.dev
    volumes:
      - .:/usr/src
      - ./.volumes/results-target:/usr/src/target
      - ./.volumes/results-registry/:/usr/local/cargo/registry
    depends_on:
      - db
      - sqs
    restart: always
    extends:
      file: common-compose.yml
      service: results
    environment:
      - RUST_LOG=debug
  s3:
    extends:
      file: common-compose.yml
      service: s3
    ports:
      - 9000:9000
      - 9999:9999
  createbuckets:
    depends_on:
      - s3
    extends:
      file: common-compose.yml
      service: createbuckets

  sqs:
    extends:
      file: common-compose.yml
      service: sqs
    ports:
      - 9324:9324

volumes:
  database:
    external: false
  minio:
    external: false
