[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-config = "0.55.2"
aws-sdk-s3 = "0.28.0"
serde = { version = "1.0.152", features = ["derive"] }
aws-sdk-sqs = "0.28.0"
tokio = {version = "1.28.1", features=["rt", "macros", "rt-multi-thread", "time", "process"]}